### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by cvandeplas** [dnsdb/dnsdb-query#38]
PR #30 added python3 compatibility, however after being merged @hstern said
> I had to revert this commit. It broke some python 2.7 stuff.

Can you expand on what it broke? A quick test with both pythons doesn't cause issues.
I'm trying to use the dnsdb library to add an expansion plugin in python3 software, like MISP-modules.

If needed I can spend some time to try to fix things and make it python3 compatible in the few missing places. Not being python3 compatible is becoming a real pain. And cherry picking the #30 commits is not very practical.

Thanks
Christophe

**Comment by mwander** [comment]
Is 2.7 support really required as of today? I'd suggest to switch to 3 and deprecate 2.7.

**Comment by hstern** [comment]
Hi @mwander . This has been replaced by github.com/dnsdb/dnsdb2-python (dnsdb2 on pypi) which is Python 3-only.
